test: remove deprecated test for ObjectId timestamp and date

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,6 +30,11 @@ jobs:
         run: |
           mkdir -p ~/.m2
           cp docs/development/maven/settings.xml ~/.m2/settings.xml
+          cat ~/.m2/settings.xml
+          # Check scent-bom can be downloaded
+          if ! curl --fail --silent --show-error http://static.platonai.cn/repo/ai/platon/scent/scent-bom/3.0.3/scent-bom-3.0.3.pom; then
+            echo "Failed to download scent-bom-3.0.3.pom" && exit 1
+          fi
 
       - name: Read VERSION
         id: version
diff --git a/.github/workflows/code-quality.yml b/.github/workflows/code-quality.yml
--- a/.github/workflows/code-quality.yml
+++ b/.github/workflows/code-quality.yml
@@ -28,6 +28,16 @@ jobs:
           java-version: 17
           cache: maven
 
+      - name: Configure Maven settings.xml if missing
+        run: |
+          mkdir -p ~/.m2
+          cp docs/development/maven/settings.xml ~/.m2/settings.xml
+          cat ~/.m2/settings.xml
+          # Check scent-bom can be downloaded
+          if ! curl --fail --silent --show-error http://static.platonai.cn/repo/ai/platon/scent/scent-bom/3.0.3/scent-bom-3.0.3.pom; then
+            echo "Failed to download scent-bom-3.0.3.pom" && exit 1
+          fi
+
       - name: Cache Maven packages
         uses: actions/cache@v3
         with:
